version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=pg.suilabs.com
      - LETSENCRYPT_HOSTpg.=suilabs.com
      - LETSENCRYPT_EMAIL=borja.arias.upc@gmail.com
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  service:
    depends_on:
      - db
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
volumes:
  db:
    driver: local