# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: gradle:7.4
    steps:
      - checkout
      - run: gradle build --no-daemon
      - run: mkdir jars
      - run: cp ./build/libs/*.jar ./jars/spring-boot-application.jar
      - persist_to_workspace:
          root: build
          paths:
            - libs
  release:
    docker:
      - image: circleci/node:lts

    environment:
      LC_DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      LC_DB_USERNAME: ${DB_USERNAME}
      LC_DB_PASSWORD: ${DB_PASSWORD}
    steps:
        - attach_workspace:
            at: /tmp/workspace
        - checkout
        - run: mkdir jars
        - run: cp -r /tmp/workspace/libs ./
        - run: ls -la
        - deploy:
            command: |
              sudo apt update
              sudo apt install -y rsync
              cd scripts
              bash updateRepo.sh >/dev/null
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          context:
            - postgres_db
          filters:
            branches:
              only: master
          requires:
            - build
